name: Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install
      run: |
        npm ci
        npm install

    - name: up docker
      run: docker-compose up -d

    - name: build app
      run: npm run build

    - name: migrations
      run: typeorm migration:run

    - name: test
      run: |
        npm test
        npm run test:cov
        npm run test:e2e

    - name: lint
      run: npm run lint
